variables:
  configuration: Release
  platform: x64
  prebuiltDxcUrl_Windows: 'https://ci.appveyor.com/api/buildjobs/pbdm27gjsfanbe9h/artifacts/build/Release/dxc-artifacts.zip'
  prebuiltDxcUrl_Linux: 'https://ci.appveyor.com/api/buildjobs/cst4bjftxe2n1t0n/artifacts/build/dxc-artifacts.tar.gz'
  prebuiltDxcExtract_Windows: '7z x -odxc-artifacts dxc-artifacts.zip'
  prebuiltDxcExtract_Linux: 'tar -xvf dxc-artifacts.tar.gz'
  testCommand_Windows: './$(buildFolder)/bin/ShaderConductorTest.exe'
  testCommand_Linux: './$(buildFolder)/bin/ShaderConductorTest'
  testCommand_macOS: './$(buildFolder)/bin/ShaderConductorTest'
  artifactBinaries_Windows: |
    bin/ShaderConductor.dll
    bin/ShaderConductorCmd.exe
    bin/dxcompiler.dll
    lib/ShaderConductor.lib
  artifactBinaries_Linux: |
    bin/ShaderConductorCmd
    lib/libdxcompiler.so
    lib/libShaderConductor.so
  artifactBinaries_macOS: |
    bin/ShaderConductorCmd
    lib/libdxcompiler.dylib
    lib/libShaderConductor.dylib

resources:
- repo: self
  fetchDepth: 5

stages:
- stage: ClangFormat
  jobs:
  - job: ClangFormat
    pool:
      vmImage: Ubuntu-20.04

    variables:
      CC: gcc
      CXX: g++

    steps:
    - bash: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install clang-format-10 ninja-build python3
      displayName: 'Install'
    - task: PythonScript@0
      displayName: 'Build'
      inputs:
        scriptPath: BuildAll.py
        arguments: 'ninja gcc linux clangformat'
    - script: |
        git diff --exit-code $(Build.SourceVersion)
      failOnStderr: true
      displayName: 'Clang-Format'

- stage: Build
  condition: succeeded('ClangFormat')
  jobs:
  - job: Build
    strategy:
      matrix:
        Windows_vc142_x86:
          vmImage: windows-2019
          compiler: vc142
          platform: x86
          combination: 'win-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: 'choco install ninja wget'
          testCommand: $(testCommand_Windows)
          artifactBinaries: $(artifactBinaries_Windows)
        Windows_vc142_x64:
          vmImage: windows-2019
          compiler: vc142
          combination: 'win-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: 'choco install ninja wget'
          prebuiltDxcDir: '$(Agent.TempDirectory)/dxc-artifacts'
          prebuiltDxcUrl: $(prebuiltDxcUrl_Windows)
          prebuiltDxcExtract: $(prebuiltDxcExtract_Windows)
          testCommand: $(testCommand_Windows)
          artifactBinaries: $(artifactBinaries_Windows)
        Windows_vc142_arm64:
          vmImage: windows-2019
          compiler: vc142
          platform: arm64
          combination: 'win-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: 'choco install ninja wget'
          artifactBinaries: $(artifactBinaries_Windows)
        Windows_vc143_x64:
          vmImage: windows-2022
          compiler: vc143
          combination: 'win-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: 'choco install ninja wget'
          prebuiltDxcDir: '$(Agent.TempDirectory)/dxc-artifacts'
          prebuiltDxcUrl: $(prebuiltDxcUrl_Windows)
          prebuiltDxcExtract: $(prebuiltDxcExtract_Windows)
          testCommand: $(testCommand_Windows)
          artifactBinaries: $(artifactBinaries_Windows)
        Windows_vc143_arm64:
          vmImage: windows-2022
          compiler: vc143
          platform: arm64
          combination: 'win-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: 'choco install ninja wget'
          artifactBinaries: $(artifactBinaries_Windows)
        Linux_gcc9:
          vmImage: Ubuntu-20.04
          compiler: gcc9
          combination: 'linux-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install g++-9 ninja-build python3
          prebuiltDxcDir: '$(Agent.TempDirectory)/dxc-artifacts'
          prebuiltDxcUrl: $(prebuiltDxcUrl_Linux)
          prebuiltDxcExtract: $(prebuiltDxcExtract_Linux)
          testCommand: $(testCommand_Linux)
          artifactBinaries: $(artifactBinaries_Linux)
          CC: gcc-9
          CXX: g++-9
        Linux_gcc10:
          vmImage: Ubuntu-20.04
          compiler: gcc10
          combination: 'linux-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install g++-10 ninja-build python3
          prebuiltDxcDir: '$(Agent.TempDirectory)/dxc-artifacts'
          prebuiltDxcUrl: $(prebuiltDxcUrl_Linux)
          prebuiltDxcExtract: $(prebuiltDxcExtract_Linux)
          testCommand: $(testCommand_Linux)
          artifactBinaries: $(artifactBinaries_Linux)
          CC: gcc-10
          CXX: g++-10
        Linux_clang11:
          vmImage: Ubuntu-20.04
          compiler: clang11
          combination: 'linux-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: |
            wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main"
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install clang-11 libc++-11-dev libc++abi-11-dev lld-11 ninja-build python3
          prebuiltDxcDir: '$(Agent.TempDirectory)/dxc-artifacts'
          prebuiltDxcUrl: $(prebuiltDxcUrl_Linux)
          prebuiltDxcExtract: $(prebuiltDxcExtract_Linux)
          testCommand: $(testCommand_Linux)
          artifactBinaries: $(artifactBinaries_Linux)
          CC: clang-11
          CXX: clang++-11
        Linux_clang13:
          vmImage: Ubuntu-20.04
          compiler: clang13
          combination: 'linux-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: |
            wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install clang-13 libc++-13-dev libc++abi-13-dev lld-13 ninja-build python3
          prebuiltDxcDir: '$(Agent.TempDirectory)/dxc-artifacts'
          prebuiltDxcUrl: $(prebuiltDxcUrl_Linux)
          prebuiltDxcExtract: $(prebuiltDxcExtract_Linux)
          testCommand: $(testCommand_Linux)
          artifactBinaries: $(artifactBinaries_Linux)
          CC: clang-13
          CXX: clang++-13
        macOS_10_clang:
          vmImage: macOS-10.15
          compiler: clang9
          combination: 'osx-$(compiler)-$(platform)-$(configuration)'
          buildFolder: 'Build/ninja-$(combination)'
          installCommand: brew install ninja
          testCommand: $(testCommand_macOS)
          artifactBinaries: $(artifactBinaries_macOS)
          CC: clang
          CXX: clang++

    pool:
      vmImage: $(vmImage)

    steps:
      - bash: eval '$(installCommand)'
        displayName: 'Install'

      - script: |
          git config --global user.email "dummy@example.com"
          git config --global user.name "Dummy Name"
        displayName: 'Config git'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'

      - bash: |
          wget $(prebuiltDxcUrl)
          eval '$(prebuiltDxcExtract)'
        workingDirectory: $(Agent.TempDirectory)
        displayName: 'Download DXC package'
        condition: ne(variables.prebuiltDxcUrl, '')
        continueOnError: true

      - task: Cache@2
        inputs:
          key: 'Build | External/DirectXShaderCompiler.cmake | $(combination)'
          restoreKeys: |
            Build | $(combination)
          path: $(buildFolder)/External/DirectXShaderCompiler
        displayName: Cache Build

      - task: Cache@2
        inputs:
          key: 'External | External/CMakeLists.txt | External/*.cmake | $(combination)'
          restoreKeys: |
            External | $(combination)
          path: External
        displayName: Cache External

      - task: PythonScript@0
        displayName: 'Build'
        inputs:
          scriptPath: BuildAll.py
          arguments: 'ninja $(compiler) $(platform) $(configuration)'

      - bash: eval '$(testCommand)'
        displayName: 'Test'
        condition: ne(variables.testCommand, '')

      - bash: 'echo $BUILD_SOURCEVERSION > $BUILD_ARTIFACTSTAGINGDIRECTORY/GIT-COMMIT.txt'
        displayName: 'Add commit info'

      - task: CopyFiles@2
        displayName: 'Copy Headers'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: Include/ShaderConductor/ShaderConductor.hpp
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: CopyFiles@2
        displayName: 'Copy Binaries'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/$(buildFolder)'
          Contents: $(artifactBinaries)
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: ShaderConductor-$(combination)
